language: node_js
node_js:
   - "10.16.3"
cache: 
  directories: 
     - node_modules
before_install:
   - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
   - export PATH="$HOME/.yarn/bin:$PATH"
services:
   - mongodb
before_script:
   - yarn
   - sleep 15
   - mongo tendered --eval 'db.createUser({user:"sirphemmiey",pwd:"Algorithm212...",roles:["readWrite"]});'
script:
  - echo 'Testing!'
  - yarn test
after_success: yarn coverage