# ---- Base Node ----
FROM node:12.2.0-alpine AS base

# Create opt directory
WORKDIR /opt


# ---- Dependencies ----
FROM base AS dependencies

# Install yarn and other dependencies via apk
RUN apk update && apk add git python g++ make && rm -rf /var/cache/apk/*

COPY package*.json ./

# Install app dependencies
RUN npm install


# ---- Release ----
FROM dependencies AS release

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]